name: Docker image build and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: docker image build
        run: docker build -t 91221881/flask-redis:latest .
      - name: list docker image
        run: docker image ls
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: docker push
        run: docker image push 91221881/flask-redis:latest
        
